// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/src/Json_decode.js");

function prices(json) {
  return /* record */[
          /* nasdaq */Json_decode.field("nasdaq", Json_decode.$$int, json),
          /* cac40 */Json_decode.field("cac40", Json_decode.$$int, json)
        ];
}

function stockItem(json) {
  return /* record */[
          /* timestamp */Json_decode.field("timestamp", Json_decode.$$int, json),
          /* index */Json_decode.field("index", Json_decode.$$int, json),
          /* stocks */Json_decode.field("stocks", prices, json)
        ];
}

var Decode = /* module */[
  /* prices */prices,
  /* stockItem */stockItem
];

var fetchdata = fetch("http://localhost:8000").then((function (prim) {
          return prim.text();
        })).then((function (jsonText) {
        return Promise.resolve(JSON.parse(jsonText));
      }));

console.log(fetchdata);

var baseUrl = "https://localhost:8000";

exports.baseUrl   = baseUrl;
exports.Decode    = Decode;
exports.fetchdata = fetchdata;
/* fetchdata Not a pure module */
