// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Micro = require("micro");

var data_file = "stocks.json";

var file_content = Fs.readFileSync(data_file, "utf8");

function add(a, b) {
  return a + b | 0;
}

var server = Micro(function (_req, _res) {
      return file_content;
    });

console.log("http://localhost:" + 8000 + "/");

server.listen(8000);

var baseUrl = "https://localhost:8000";

var port = 8000;

exports.baseUrl = baseUrl;
exports.data_file = data_file;
exports.file_content = file_content;
exports.port = port;
exports.add = add;
exports.server = server;
/* file_content Not a pure module */
