// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("@glennsl/bs-json/src/Json_decode.bs.js");

function prices(json) {
  return {
          nasdaq: Json_decode.field("nasdaq", Json_decode.$$int, json),
          cac40: Json_decode.field("cac40", Json_decode.$$int, json)
        };
}

function stockItem(json) {
  return {
          timestamp: Json_decode.field("timestamp", Json_decode.$$int, json),
          index: Json_decode.field("index", Json_decode.$$int, json),
          stocks: Json_decode.field("stocks", prices, json)
        };
}

var Decode = {
  prices: prices,
  stockItem: stockItem
};

exports.Decode = Decode;
/* No side effect */
